apiVersion: v1
kind: Service
metadata:
  name: app-postgres
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: app-postgres
  ports:
    - name: app-postgres
      port: 3306
      targetPort: 3306
