apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-mongo
  namespace: production
spec:
  selector:
    matchLabels:
      app: app-mongo
  serviceName: app-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: app-mongo
    spec:
      containers:
        - name: app-mongo
          image: mongo:7.0.4
          ports:
            - containerPort: 27017
              name: app-mongo
          volumeMounts:
            - name: mongo-local-storage
              mountPath: /data/db
      volumes:
        - name: mongo-local-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
