apiVersion: v1
kind: Service
metadata:
  name: app-redis
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: app-redis
  ports:
    - name: app-redis
      port: 6379
      targetPort: 6379
