apiVersion: v1
kind: Service
metadata:
  name: app-mysql
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: app-mysql
  ports:
    - name: app-mysql
      port: 3306
      targetPort: 3306
